basePath: /v2
definitions:
  handler.StatusError:
    properties:
      code:
        type: integer
      err:
        type: error
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /customers/get/{id}:
    get:
      consumes:
      - application/json
      description: get customer info by ID
      parameters:
      - description: Some ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.StatusError'
            type: object
      tags:
      - customers
swagger: "2.0"
